### PR TITLE
Add config parameter to disable copying compile commands

### PR DESCRIPTION
**Pull request by JafarAbdi**
Sometimes this file could be big so it would be great to have an option to disable copying it

### CODE REVIEW

**Comment by Shatur** [comment]
Could you update the readme?

**Comment by JafarAbdi** [comment]
I use the same file in https://github.com/Shatur/neovim-cmake/pull/40#issuecomment-1144841567 to explicitly pass the "--compile-commands-dir=" option to clangd which doesn't require copying

**Comment by Shatur** [comment]
Hm... I wonder if we could avoid copying at all and always use the mentioned flag. What do you think?

**Comment by Shatur** [comment]
Oh, right. Okay, let's introduce this feature. Please, update the readme and I will merge it.

**Pull request merged**
